stages:

  download:
    cmd: python3 main.py --download-data
    deps:
      - src/protx/data/downloader.py
    params:
      - data_dirs.uniref50_url
      - data_dirs.uniref50_fasta_gz
    outs:
      - output/data/raw/uniref50.fasta.gz

  extract:
    cmd: python3 main.py --extract-data
    deps:
      - src/protx/data/extractor.py
      - output/data/raw/uniref50.fasta.gz
    params:
      - data_dirs.uniref50_fasta_gz
      - data_dirs.uniref50_fasta
    outs:
      - output/data/raw/uniref50.fasta

  filter_split:
    cmd: python3 main.py --filter-split-data
    deps:
      - src/protx/data/filter_splitor.py
      - output/data/raw/uniref50.fasta
    params:
      - data_dirs.uniref50_fasta
      - data_dirs.filter_split_dir
      - data_dirs.info_file
      - data_params.min_seq_len
      - data_params.max_seq_len
      - data_params.max_seqs_num
      - data_params.val_ratio
    outs:
      - output/data/filter_split/uniref50_filtered.fasta
      - output/data/filter_split/train.fasta
      - output/data/filter_split/val.fasta
      - output/data/filter_split/dataset_info.txt
  
  save_protx_dataset:
    cmd: python3 main.py --save-protx-dataset
    deps:
      - src/protx/data/dataset.py
      - output/data/filter_split/train.fasta
      - output/data/filter_split/val.fasta
    params:
      - data_dirs.protx_dataset_dir
      - data_dirs.protx_train_prefix
      - data_dirs.protx_val_prefix
      - data_params.embed_calc_batch_size
      - data_params.seqs_num_per_file
    outs:
      - output/data/protx_dataset/train/
      - output/data/protx_dataset/val/
  
  train_model:
    cmd: python3 main.py --train-model
    deps:
      - src/protx/distillation/pipeline.py
      - output/data/protx_dataset/
    params:
      - distill_params.student_embed_dim
      - distill_params.student_num_layers
      - distill_params.student_num_heads
      - distill_params.on_the_fly
      - distill_params.num_epochs
      - distill_params.batch_size
      - distill_params.start_lr
      - distill_params.warmup_steps
      - distill_params.min_lr
      - distill_params.max_lr
      - distill_params.T_0
      - distill_params.T_mult
      - distill_params.gamma
      - distill_params.max_cycle_length
