stages:

  download:
    cmd: protx download-data
      --url ${data_dirs.uniref50_url}
      --output ${data_dirs.uniref50_fasta_gz}
    deps:
      - src/protx/data/downloader.py
    params:
      - data_dirs.uniref50_url
      - data_dirs.uniref50_fasta_gz
    outs:
      - ${data_dirs.uniref50_fasta_gz}

  extract:
    cmd: protx extract-data
      --input ${data_dirs.uniref50_fasta_gz}
      --output ${data_dirs.uniref50_fasta}
    deps:
      - src/protx/data/extractor.py
      - ${data_dirs.uniref50_fasta_gz}
    params:
      - data_dirs.uniref50_fasta_gz
      - data_dirs.uniref50_fasta
    outs:
      - ${data_dirs.uniref50_fasta}

  filter_split:
    cmd: protx filter-split-data
      --input ${data_dirs.uniref50_fasta}
      --filtered-seqs ${data_dirs.uniref50_filtered_fasta}
      --train-file ${data_dirs.train_fasta}
      --val-file ${data_dirs.val_fasta}
      --min-seq-len ${data_params.min_seq_len}
      --max-seq-len ${data_params.max_seq_len}
      --max-seqs-num ${data_params.max_seqs_num}
      --val-ratio ${data_params.val_ratio}
      --info-file ${data_dirs.info_file}
      --shuffle ${data_params.shuffle}
    deps:
      - src/protx/data/filter_splitor.py
      - ${data_dirs.uniref50_fasta}
    params:
      - data_dirs.uniref50_fasta
      - data_dirs.uniref50_filtered_fasta
      - data_dirs.info_file
      - data_params.min_seq_len
      - data_params.max_seq_len
      - data_params.max_seqs_num
      - data_params.val_ratio
    outs:
      - ${data_dirs.uniref50_filtered_fasta}
      - ${data_dirs.train_fasta}
      - ${data_dirs.val_fasta}
      - ${data_dirs.info_file}
  
  save_protx_train_dataset:
    cmd: protx save-protx-dataset
      --input-file ${data_dirs.train_fasta}
      --teacher-model 'prott5'
      --output-file ${data_dirs.protx_train_prefix}
      --max-seq-len ${data_params.max_seq_len}
      --batch-size ${data_params.embed_calc_batch_size}
      --device 'auto'
    deps:
      - src/protx/data/dataset.py
      - ${data_dirs.train_fasta}
    params:
      - data_dirs.train_fasta
      - data_dirs.protx_train_prefix
      - data_params.embed_calc_batch_size

  save_protx_val_dataset:
    cmd: protx save-protx-dataset
      --input-file ${data_dirs.val_fasta}
      --teacher-model 'prott5'
      --output-file ${data_dirs.protx_val_prefix}
      --max-seq-len ${data_params.max_seq_len}
      --batch-size ${data_params.embed_calc_batch_size}
      --device 'auto'
    deps:
      - src/protx/data/dataset.py
      - ${data_dirs.val_fasta}
    params:
      - data_dirs.protx_dataset_dir
      - data_dirs.protx_val_prefix
      - data_params.embed_calc_batch_size
  
  train_model:
    cmd: torchrun --nproc_per_node=4 --nnodes=1 --master_port=29500 /usr/local/bin/protx train-student
    deps:
      - src/protx/distillation/pipeline.py
      - output/data/protx_dataset/
    params:
      - distill_params.student_embed_dim
      - distill_params.student_num_layers
      - distill_params.student_num_heads
      - distill_params.on_the_fly
      - distill_params.num_epochs
      - distill_params.batch_size
      - distill_params.warmup_steps
      - distill_params.min_lr
      - distill_params.max_lr
      - distill_params.dataloader_num_workers
