data_params:
  val_ratio: 0.1
  max_seqs_num: 100
  min_seq_len: 20
  max_seq_len: 512

data_dirs:
  uniref50_url: "https://ftp.uniprot.org/pub/databases/uniprot/knowledgebase/complete/uniprot_sprot.fasta.gz" 
  uniref50_fasta_gz: "output/data/raw/uniref50.fasta.gz"

  base_dir: "output/data"
  raw_dir: "output/data/raw"

  uniref50_fasta: "output/data/raw/uniref50.fasta"

  filter_split_dir: "output/data/filter_split"
  uniref50_filtered_fasta: "output/data/filter_split/uniref50_filtered.fasta"
  train_fasta: "output/data/filter_split/train.fasta"
  val_fasta: "output/data/filter_split/val.fasta"
  info_file: "output/data/filter_split/dataset_info.txt"

  protx_dataset_dir: "output/data/protx_dataset"
  protx_train: "output/data/protx_dataset/train.h5"
  protx_val: "output/data/protx_dataset/val.h5"

