data_params:
  val_ratio: 0.1
  max_seqs_num: 1000
  min_seq_len: 20
  max_seq_len: 512

distill_params:

  # student
  student_embed_dim: 512
  student_num_layers: 6
  student_num_heads: 8

  on_the_fly: false
  num_epochs: 15
  batch_size: 64

  # scheduler
  ## warmup
  start_lr: 1e-8
  warmup_steps: 500

  ## cosine annealing
  min_lr: 1e-5
  max_lr: 3e-3
  T_0: 100
  T_mult: 1.25
  gamma: 0.55

  max_cycle_length: null


### DO NOT CHANGE CONFIGS BELOW ###
data_dirs:
  uniref50_url: "https://ftp.uniprot.org/pub/databases/uniprot/knowledgebase/complete/uniprot_sprot.fasta.gz" 
  uniref50_fasta_gz: "output/data/raw/uniref50.fasta.gz"

  base_dir: "output/data"
  raw_dir: "output/data/raw"

  uniref50_fasta: "output/data/raw/uniref50.fasta"

  filter_split_dir: "output/data/filter_split"
  uniref50_filtered_fasta: "output/data/filter_split/uniref50_filtered.fasta"
  train_fasta: "output/data/filter_split/train.fasta"
  val_fasta: "output/data/filter_split/val.fasta"
  info_file: "output/data/filter_split/dataset_info.txt"

  protx_dataset_dir: "output/data/protx_dataset"
  protx_train: "output/data/protx_dataset/train.h5"
  protx_val: "output/data/protx_dataset/val.h5"

  wandb_checkpoints_dir: "output/data/wandb_checkpoints"
  plots_dir: "output/data/plots"
