data_params:
  val_ratio: 0.1
  max_seqs_num: 1_000_000
  min_seq_len: 20
  max_seq_len: 512
  # This batch size is used for embedding calculation
  embed_calc_batch_size: 64
  seqs_num_per_file: 10_000
  shuffle: true

distill_params:
  dataloader_num_workers: 4

  # student
  student_embed_dim: 512
  student_num_layers: 6
  student_num_heads: 8

  on_the_fly: false
  num_epochs: 10
  batch_size: 64

  # scheduler
  ## warmup
  warmup_steps: 1000

  ## cosine annealing
  min_lr: 1e-5
  max_lr: 3e-3


### DO NOT CHANGE CONFIGS BELOW ###
data_dirs:
  uniref50_url: "https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref50/uniref50.fasta.gz" 
  uniref50_fasta_gz: "output/data/raw/uniref50.fasta.gz"

  base_dir: "output/data"
  raw_dir: "output/data/raw"

  uniref50_fasta: "output/data/raw/uniref50.fasta"

  filter_split_dir: "output/data/filter_split"
  uniref50_filtered_fasta: "output/data/filter_split/uniref50_filtered.fasta"
  train_fasta: "output/data/filter_split/train.fasta"
  val_fasta: "output/data/filter_split/val.fasta"
  info_file: "output/data/filter_split/dataset_info.txt"

  protx_dataset_dir: "output/data/protx_dataset"
  protx_train_prefix: "output/data/protx_dataset/train/train"
  protx_val_prefix: "output/data/protx_dataset/val/val"

  wandb_checkpoints_dir: "output/wandb_checkpoints"
  plots_dir: "output/checkpoints/plots"
