[project]
name = "ProtX"
version = "0.1.0"
description = "Knowledge distillation of ProtT5"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.85",
    "dvc>=3.59.1",
    "h5py>=3.13.0",
    "ipykernel>=6.29.5",
    "onnx>=1.18.0",
    "pyyaml>=6.0.2",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "transformers>=4.50.2",
    "wandb>=0.19.11",
]
